import { SIZES, TYPES, CATEGORIES } from './constants';

export const products = [
  {
    id: 'c1',
    name: 'Manzana',
    mesures: 'Alto: 30 cm, Base: 20x20 cm',
    prix: 10000,
    userPrix: 18000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [CATEGORIES.RESTAURANTE, CATEGORIES.HOGAR],
  },
  {
    id: 'c2',
    name: 'Mixto con cabestro',
    mesures: 'Alto: 20 cm, Boca: 31 cm',
    prix: 12000,
    userPrix: 20000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c3',
    name: 'Tambor',
    mesures: 'Alto: 9 cm, Base: 20 cm',
    prix: 10000,
    userPrix: 18000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c4',
    name: 'Florera',
    mesures: 'Alto: 20 cm, Base: 20 cm',
    prix: 12000,
    userPrix: 20000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c5',
    name: 'Pantalla medio balón',
    mesures: 'Alto: 35 cm, Boca: 35 cm',
    prix: 18000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c6',
    name: 'Ollita gigante',
    mesures: 'Alto: 40 cm, Base: 40 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c7',
    name: 'Estrella',
    mesures: 'Alto: 13 cm, Base: 22 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c8',
    name: 'Bolso Cabestro',
    mesures: 'Alto: 18 cm, Base: 20 x 15 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c9',
    name: 'Media canoa',
    mesures: 'Alto: 11 x 16 cm, Base: 30 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c10',
    name: 'Frutero',
    mesures: 'Alto: 12 cm, Base: 34 x 23 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c11',
    name: 'Ponchera',
    mesures: 'Alto: 12 cm, Base: 22 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c12',
    name: 'San Jose',
    mesures: 'Alto: 7 cm, Base: 7 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c13',
    name: 'Pantalla gigante',
    mesures: 'Alto: 45 cm, Base: 48 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c14',
    name: 'Frutero especial',
    mesures: 'Alto: 15 cm, Base: 30 x 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c15',
    name: 'Ollita',
    mesures: 'Alto: 14 cm, Base: 18 x 18 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c16',
    name: 'Pantalla Platillo',
    mesures: 'Boca 60cm de largo y 30 cm en angosto',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c17',
    name: 'Pantalla Mixta',
    mesures: 'Alto: 25 cm, Base: 30 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c18',
    name: 'Pantalla cuadrada',
    mesures: 'Alto: 20 cm, Base: 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c19',
    name: 'Uchubo gigante',
    mesures: 'Alto: 40 cm, Base: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c20',
    name: 'Pantalla cilindro',
    mesures: 'Alto: 25 cm, Boca: 15 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c21',
    name: 'Bandeja chineada',
    mesures: 'Alto: 20 cm, Base: 30 x 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c22',
    name: 'Cantina',
    mesures: 'Alto: 31 cm, Base: 20 cm, Boca: 16 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c23',
    name: 'Florera sombrero',
    mesures: 'Alto: 15 cm, Base: 20 cm, ALla: 9 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c24',
    name: 'Pantalla calada',
    mesures: 'Alto: 35 cm, Base: 35 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c25',
    name: 'Panera',
    mesures: 'Alto: 13 cm, Base: 49 x 36 cm, Boca: 55 x 41 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c26',
    name: 'Bolso gigante',
    mesures: 'Alto: 30 cm, Base: 29 x 15 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c27',
    name: 'Paragüero',
    mesures: 'Alto: 60 cm, Base: 30 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c28',
    name: 'Sombrero Charro',
    mesures: 'Alto: 50 cm + 20 cm de ala, Boca: 55 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c29',
    name: 'Papelera fina',
    mesures: 'Alto: 15 cm, Base: 20 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c30',
    name: 'Baguette',
    mesures: 'Alto: 30 cm, Base: 22 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c31',
    name: 'Papelera corriente',
    mesures: 'Alto: 18 cm, Base: 20 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c32',
    name: 'Panera pintada',
    mesures: 'Alto: 15 cm de espalda y 12 cm de frente, Base: 60 x 45 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c33',
    name: 'Media luna',
    mesures: 'Alto: 22 cm, Base: 22 x 10 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c34',
    name: 'Boquinche',
    mesures: 'Alto: 20 cm de espalda y 10 cm de frente, Base: 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c35',
    name: 'Funda de botella',
    mesures: '',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c36',
    name: 'Evel con tapa',
    mesures: 'Alto: 8 cm, Base: 30 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c37',
    name: 'Perrero',
    mesures: 'Alto: 35 cm de espalda y 10 cm de frente, Base: 50 x 40 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c38',
    name: 'Bandeja tejida',
    mesures: 'Alto: 10 cm, Base: 30 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c39',
    name: 'Revistero base tejida',
    mesures: 'Alto: 20 cm, Base: 20 cm, Boca: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c40',
    name: 'Mandadero',
    mesures: 'Alto: 20 cm, Base: 20 cm, Boca: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c41',
    name: 'Papelera sesgo',
    mesures: 'Alto: 20 cm, Base: 20 cm, Boca: 30 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c42',
    name: 'Bandeja melcocha',
    mesures: 'Alto: 12 cm, Base: 30 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c43',
    name: 'Corazón',
    mesures: '',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c44',
    name: 'Jarrones',
    mesures: 'Alto: 40 30 y 20 cm, Base: 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c45',
    name: 'Ancheta',
    mesures: 'Alto: 20 cm, Base: 30 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c46',
    name: 'Ancheta tejida',
    mesures: 'Alto: 20 cm, Base: 22 x 15 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c47',
    name: 'Porta-objetos tejido',
    mesures: 'Alto: 15 cm, Base: 30 x 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c48',
    name: 'Florero Aros',
    mesures: 'Alto: 15 cm, Base: 20 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c49',
    name: 'Papelera especial',
    mesures: 'Alto: 20 cm, Base: 20 cm, Boca: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c50',
    name: 'Papelera natural',
    mesures: 'Alto: 15 cm, Base: 20 cm, Boca: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c51',
    name: 'Evel con cabestro',
    mesures: 'Alto: 7 cm, Base: 21 x 16 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c52',
    name: 'Panera tejida',
    mesures: 'Alto: 12 cm, Base: 25 x 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c53',
    name: 'Ponchera',
    mesures: 'Alto: 10 cm, Base: 22 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c54',
    name: 'Bandeja ovalada ',
    mesures: 'Alto: 7 cm, Base: 24 x 14 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c55',
    name: 'Baul chineado',
    mesures: 'Alto: 15 cm, Base: 40 x 30 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c56',
    name: 'Pantalla Farol',
    mesures: 'Alto: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c57',
    name: 'Individuales redondos',
    mesures: 'Diámetro: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c58',
    name: 'Individuales rectangulares',
    mesures: 'Largo: 30 cm, Ancho: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c59',
    name: 'Evel',
    mesures: 'Alto: 7 cm, Base: 21 x 16 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c60',
    name: 'Tres puntas',
    mesures: 'Alto: 10 y 13 cm, Base: 19 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c61',
    name: 'Bandeja Canoa',
    mesures: 'Alto: 10 y 13 cm, Base: 29 x 19.5 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c62',
    name: 'Cubiertero',
    mesures: 'Alto: 5.5 cm, Base: 8 x 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c63',
    name: 'Casuelero',
    mesures: 'Alto: 5.5 cm, Base: 12 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c64',
    name: 'Bandeja redonda',
    mesures: 'Alto: 6.5 cm, Base: 19.5 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c65',
    name: 'Papelera ondulada',
    mesures: 'Alto: 18 y 20 cm, Base: 19.5 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c66',
    name: 'Uchuvo',
    mesures: 'Alto: 15 cm, Base: 18 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.SMALL,
    promo: 0,
    categories: [],
  },
  {
    id: 'c67',
    name: 'Canasto calado',
    mesures: 'Alto: 20 cm, Base: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c68',
    name: 'Detallitos',
    mesures: 'Alto: 15 cm, Base: 29 x 15 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c69',
    name: 'Pantalla Calada',
    mesures: 'Alto: 50 cm, Boca: 50 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c70',
    name: 'Pantalla moñito',
    mesures: 'Alto: 36 cm, Boca: 36 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c71',
    name: 'Pantalla chineada',
    mesures: 'Alto: 25 cm, Boca: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c72',
    name: 'Pantalla Arcos',
    mesures: 'Alto: 35 cm, Boca: 35 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c73',
    name: 'Pantalla Calada Pequeña',
    mesures: 'Alto: 35 cm, Boca: 35 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c74',
    name: 'Pantalla Media Chineada',
    mesures: 'Alto: 30 cm, Boca: 30 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c75',
    name: 'Orquidea',
    mesures: 'Alto: 10 y 20 cm, Base: 25 x 16 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c76',
    name: 'Pantalla Aros',
    mesures: 'Alto: 50 cm, Boca: 50 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.PANTALLA,
    size: SIZES.LARGE,
    promo: 0,
    categories: [],
  },
  {
    id: 'c77',
    name: 'Jarrón Egipcio',
    mesures: 'Alto: 100 cm, Boca: 30 cm, Base: 20 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
  {
    id: 'c78',
    name: 'Balón',
    mesures: 'Alto: 50 cm, Boca: 25 cm',
    prix: 15000,
    userPrix: 30000,
    imageUrl: '',
    type: TYPES.CANASTO,
    size: SIZES.MEDIUM,
    promo: 0,
    categories: [],
  },
];
